// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEnpOJbfryTwX1htuEBRaCLqyd9IGm-tA',
    appId: '1:722192984616:web:c014efa46ea4468dc8a31d',
    messagingSenderId: '722192984616',
    projectId: 'girman-ace5c',
    authDomain: 'girman-ace5c.firebaseapp.com',
    storageBucket: 'girman-ace5c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp-hnYrXLC3wn01sNKaaYX3q3J3wBSbWs',
    appId: '1:722192984616:android:8b78386f1622f3b7c8a31d',
    messagingSenderId: '722192984616',
    projectId: 'girman-ace5c',
    storageBucket: 'girman-ace5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP2nJjqD0qA3oLO9S53UVt7JRLWsVaOtU',
    appId: '1:722192984616:ios:02fee9243bf8f3f4c8a31d',
    messagingSenderId: '722192984616',
    projectId: 'girman-ace5c',
    storageBucket: 'girman-ace5c.appspot.com',
    iosBundleId: 'com.example.girman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP2nJjqD0qA3oLO9S53UVt7JRLWsVaOtU',
    appId: '1:722192984616:ios:02fee9243bf8f3f4c8a31d',
    messagingSenderId: '722192984616',
    projectId: 'girman-ace5c',
    storageBucket: 'girman-ace5c.appspot.com',
    iosBundleId: 'com.example.girman',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEnpOJbfryTwX1htuEBRaCLqyd9IGm-tA',
    appId: '1:722192984616:web:1882f3bc1103ce2bc8a31d',
    messagingSenderId: '722192984616',
    projectId: 'girman-ace5c',
    authDomain: 'girman-ace5c.firebaseapp.com',
    storageBucket: 'girman-ace5c.appspot.com',
  );
}
